# Base Configuration
baseURL = "https://michaeltatum.xyz/" # Added trailing slash for consistency, Hugo often handles it but explicit can be clearer
theme = ["hugo-embed-pdf-shortcode", "risotto"]
title = "Michael Tatum"
author = "A. Michael Tatum"
copyright = "© 2025 AMT"
paginate = 3
languageCode = "en"
# DefaultContentLanguage = "en" # Redundant if languageCode is "en" and you only use one language
enableInlineShortcodes = true
publishDir = "docs" # Common for GitHub Pages

# Performance & Build Optimizations
enableGitInfo = true       # Useful for themes displaying lastmod, etc.
enableRobotsTXT = true     # Generates a robots.txt
canonifyURLs = true        # Resolves URLs to their absolute versions based on baseURL. Good for consistency.
                           # Note: Set to false if you have complex proxy setups or need relative URLs preserved.
enableEmoji = true

# Error Handling
# Prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API
ignoreErrors = ["error-remote-getjson"]

# Menu Configuration
# sectionPagesMenu = "main" # Consider removing this if your [menu.main] below is comprehensive.
                            # If active, it automatically adds top-level sections to the 'main' menu.
                            # This might lead to duplicates or unwanted items if you precisely define the menu below.

[build]
  writeStats = true       # Generates hugo_stats.json, useful for analysis. Can be false for production if not needed.
  # noJSConfigInAssets = false # This is the default, so explicitly setting it is not necessary.

[minify]
  minifyOutput = true
  # disableXML = true # Set to false if you want your XML (RSS, sitemap) minified. True is fine if readability of XML output is preferred.
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepDocumentTags = true # Keeps <html>, <head>, <body> tags. Default is false, but true can be safer.
      keepQuotes = false      # Removes quotes around attributes where possible. Default is true.
    [minify.tdewolff.css]
      # keepCSS2 = true       # This option might not be recognized by current Hugo/tdewolff versions.
                              # Standard minification usually handles CSS versions appropriately.
      precision = 1         # Precision 0 can be too aggressive for CSS (e.g., for em, rem units). 1 is often a safer bet.
    [minify.tdewolff.js]
      # keepVarNames = false  # Default is false, so not strictly necessary to specify.
      precision = 1         # Precision 0 can be aggressive. Consider 1 or higher if you encounter issues with JS calculations.

[markup]
  [markup.goldmark.renderer]
    unsafe = true # WARNING: Allows raw HTML in Markdown. Ensure content is trusted. This is a security risk if you allow untrusted content.
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"
  [markup.highlight]
    style = "github"
    lineNos = true
    # codeFences = true # Default is true, so not strictly necessary to specify.
    guessSyntax = true
    # hl_Lines = "" # Default is empty, not strictly necessary.
    lineNumbersInTable = true # Improves copy-pasting of code with line numbers.
    noClasses = false         # Necessary for most CSS-based syntax highlighting themes.
    tabWidth = 4

[params]
  favicon = "/images/bash.png" # Assuming this is in your static folder: static/images/bash.png
  defaultImage = "/images/profile-cleaned.jpg"

  # SEO & Meta
  description = "A. Michael Tatum - Full-stack developer & systems architect. Digital CV and portfolio featuring SiftDNS and other technical projects."
  keywords = ["Michael Tatum", "Full-stack Developer", "Systems Architect", "SiftDNS", "Portfolio", "DNS Privacy"]

  [params.schema]
    authorName = "A. Michael Tatum"
    authorImage = "/images/profile-cleaned.jpg"
    sameAs = [
      "https://github.com/amaad-michael/",
      "https://www.linkedin.com/in/amaadmichael/",
      "https://instagram.com/amaad_michael/",
      "https://amaadmichael.substack.com/"
    ]

  [params.theme] # Specific to the "risotto" theme
    palette = "gruvbox-dark"
    mode = "dark-mode"

  [params.about] # Specific to the "risotto" theme
    title = "A. Michael Tatum"
    description = "Welcome! This is my digital CV."
    logo = "/images/profile-cleaned.jpg"

# Social Links (typically used by themes)
[[params.socialLinks]]
  icon = "fab fa-github"
  title = "GitHub"
  url = "https://github.com/amaad-michael/"

[[params.socialLinks]]
  icon = "fas fa-envelope"
  title = "Email"
  url = "mailto:amaad.michael@gmail.com"

[[params.socialLinks]]
  icon = "fab fa-linkedin"
  title = "LinkedIn"
  url = "https://www.linkedin.com/in/amaadmichael/"

[[params.socialLinks]]
  icon = "far fa-newspaper"
  title = "Join my newsletter"
  url = "https://amaadmichael.substack.com/welcome/"

[[params.socialLinks]]
  icon = "fa-brands fa-instagram" # Updated for Font Awesome 6+ if applicable
  title = "IG"
  url = "https://instagram.com/amaad_michael/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "afk"
    name = "AFK"
    url = "/afk/"
    weight = 20
  [[menu.main]]
    identifier = "certs"
    name = "Certs"
    url = "/certs/"
    weight = 30
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 40
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    weight = 50
  [[menu.main]]
    identifier = "siftdns"
    name = "SiftDNS Portfolio"
    url = "/siftdns/"
    weight = 60
    [menu.main.params] # Corrected nesting for target attribute
      target = "_blank"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true # Loads video on click, good for privacy and performance
  [privacy.twitter]
    disabled = false
    enableDNT = true # Respects Do Not Track header
    simple = true    # Loads tweet on click
  [privacy.instagram]
    disabled = false # Note: Hugo's built-in Instagram shortcode may have issues due to API changes.
                     # Your ignoreErrors for remote-getjson handles GET errors, but embedding might still be tricky.
    simple = true    # Loads embed on click
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true # Uses youtube-nocookie.com

[services] # Configuration for Hugo's built-in shortcodes
  [services.instagram]
    disableInlineCSS = true # Useful if your theme or custom CSS handles styling
  [services.twitter]
    disableInlineCSS = true # Useful if your theme or custom CSS handles styling

[outputs]
  home = ["HTML", "RSS", "JSON"] # JSON for headless or custom integrations
  page = ["HTML"]
  section = ["HTML", "RSS"]

[sitemap]
  changefreq = "monthly"
  # filename = "sitemap.xml" # This is the default, so not strictly necessary to specify
  priority = 0.5

[related]
  includeNewer = true
  threshold = 80
  # toLower = false # This is the default, so not strictly necessary to specify
  [[related.indices]]
    name = "keywords"
    weight = 100
  [[related.indices]]
    name = "tags"
    weight = 80
  [[related.indices]]
    name = "categories" # Hugo also considers 'date' by default with a low weight.
    weight = 60
